# site_name: My Docs
# theme:
#   name: material
#Site
site_name: Practice
site_url: https://gk0209.github.io/practice
site_author: Girish Kumar
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project
# Repository
repo_name: Go To Repository
repo_url: https://github.com/GK0209/practice.git
edit_uri: ""

# Custom Colour Pallete
extra_css:
    - stylesheets/extra.css

# Configuration
theme:
    name: material
    icon: 
        repo: fontawesome/brands/github
        # Default values, taken from mkdocs_theme.yml
    language: en
    features:
        - content.code.annotate
        - content.tooltips
        - content.tabs.link
        - navigation.expand
        - navigation.indexes
        - navigation.instant
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        # - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    palette:
        - scheme: default
          primary: cyan
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: orange
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    #favicon: assets/Innovation.png
    logo: assets/Innovation.png        

extra:
    generator: false

plugins:
   - search
   - autorefs
   - mkdocstrings
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes: 
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom


markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - meta
    - md_in_html
    - tables
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:materialx.emoji.to_svg
        emoji_index: !!python/name:materialx.emoji.twemoji
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - footnotes
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true

nav:
    - Fundamentals: fundamental/fundamental.md
    - Lab Exercise: lab/exercise.md

copyright: |
  &copy; 2022 <a href="https://github.com/GK0209"  target="_blank" rel="noopener">Girish Kumar</a>    
    